<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-20T17:33:56 IST" name="Default suite" finished-at="2023-08-20T17:34:00 IST" duration-ms="4072">
    <groups>
    </groups>
    <test started-at="2023-08-20T17:33:56 IST" name="Default test" finished-at="2023-08-20T17:34:00 IST" duration-ms="4072">
      <class name="api.request.DoPostRequest">
        <test-method signature="doGetRequest(api.requestDTO.PostRequestBodyDTO)[pri:0, instance:api.request.DoPostRequest@3f3c7bdb]" started-at="2023-08-20T17:33:56 IST" name="doGetRequest" data-provider="API-POSTRequest-Body" finished-at="2023-08-20T17:34:00 IST" duration-ms="3766" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[PostRequestBodyDTO :{name=test, salary=123, age=23}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Is Expected Equal To Actual?"false"] but found [Too Many Request Error]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Is Expected Equal To Actual?"false"] but found [Too Many Request Error]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at utils.utility.Assertions.assertTrue(Assertions.java:44)
at api.request.DoPostRequest.doGetRequest(DoPostRequest.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doGetRequest -->
      </class> <!-- api.request.DoPostRequest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
